### PR TITLE
Support GitHub Enterprise

### PR DESCRIPTION
**Pull request by nthienan**
Resolved https://github.com/wangyoucao577/assets-uploader/issues/18

### CODE REVIEW

**Comment by nthienan** [comment]
@wangyoucao577 please help to review!

**Comment by wangyoucao577** [comment]
Does it work for your Github Enterprise?

**Comment by nthienan** [comment]
> Does it work for your Github Enterprise?

yes, it does.

**Comment by nthienan** [comment]
@wangyoucao577, anything prevents this get merged?

**Comment by wangyoucao577** [comment]
> @wangyoucao577, anything prevents this get merged?

Oh, I added some comments but forgot to commit them. Please check the comments, the only thing needs to be done is dealing with the errors.

**Review by wangyoucao577 — APPROVED** [review]

**Pull request merged**
